### ISSUE TITLE
[FE]패키지 매니저 yarn-berry로 개발 환경을 세팅한다.

### ISSUE THREAD

**Issue by 4BFC** [HandWord/HandWord_Front#1]
### ⚠️Issue
- 개발을 하기 위한 환경을 세팅한다.

### ✏️Task
- [x] npm과 yarn의 차이점을 학습한다.
- [x] npm으로 yarn을 설치한다.
- [x] 선택된 페키지 메니저로 React를 설치한다.

### 🗓Next Task
- [x] Eslint& Prettier를 설치한다.
- [x] Eslint& Prettier 규칙을 정한다.
