### ISSUE TITLE
[FE] 개발환경을 설정한다.

### ISSUE THREAD

**Issue by 4BFC** [HandWord/HandWord_Front#6]
### ⚠️Issue
- 개발을 하기 위한 환경을 세팅한다.
  - 처음에 시도했던 CRA환경에서 pnp를 적용하려다 babel-loader의 계속되는 node_module 생성으로 처음 계획했던 환경 설정이 실패했었다. 따라 다시 CRA로 pnp환경을 구축해보려고 한다. 이렇게 계획이 바뀌게된 이유는 다음 [링크](https://github.com/Programming-Contents-List/TantackQuery.git "나의 고민")를 통해서 확인 할 수 있다. 

### ✏️Task
- [ ] yarn-berry를 설치한다.
- [ ] Ts의 CRA를 설치한다.
  - [ ] build와 eject를 실행해서 webpack과 babel을 관리할 수 있는 환경을 만들어 낸다.

### 🗓Next Task
- [ ] Eslint& Prettier를 설치한다.
- [ ] Eslint& Prettier 규칙을 정한다.
- [ ] .github 폴더를 추가한다.
